In [2]:
import numpy as np

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a= np.array([1,2,3,5,6,10])
a

array([ 1,  2,  3,  5,  6, 10])

In [9]:
a[3]

np.int64(5)

In [11]:
a[2] = 10
a

array([ 1,  2, 10,  5,  6, 10])

In [15]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [18]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

Multidimentional arrays

In [19]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
n[0,1]

np.int64(2)

In [26]:
n[0,1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [28]:
n[1,:]

array([4, 5, 6])

In [29]:
n[:,1]

array([20,  5,  8])

randomly generated arrays

In [45]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [46]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [48]:
np.random.seed(2)
np.random.randint(low=2, high=10, size=(5,2))

array([[2, 9],
       [7, 2],
       [8, 5],
       [4, 5],
       [2, 9]])

element wise operations

In [54]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [55]:
a + 1 

array([1, 2, 3, 4, 5])