In [20]:
import numpy as np


In [49]:
u = np.array([2, 4, 5, 6])

In [46]:
2*u

array([ 4,  8, 10, 12])

In [48]:
v = np.array([1, 0, 0, 2])

In [50]:
v


array([1, 0, 0, 2])

Multiplication

In [51]:
v.shape[0]

4

In [25]:
u.shape[0]

4

In [52]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]
    result = 0.0
    n = u.shape[0]
    
    for i in range(n):
        result = result + u[i] * v[i]
    
    return result
    

In [53]:
vector_vector_multiplication(u,v)

np.float64(14.0)

In [54]:
u.dot(v)

np.int64(14)

In [65]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])

In [66]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [73]:
v

array([1, 0, 0, 2])

In [67]:
U.shape[0]

3

In [68]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
        
    return result

In [69]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [70]:
U.dot(v)

array([14,  5,  5])

In [71]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
])

In [81]:
V.shape[1]

3

In [83]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result


In [84]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [85]:

U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

identity matrix


In [87]:
I = np.eye(3)

In [89]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [88]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [90]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

INVERSE

In [92]:
Vs = V[[0,1,2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [95]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [96]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])