In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('laptops.csv')
df.columns = df.columns.str.lower().str.replace(' ', '_')
df
# string_columns = list(df.dtypes[df.dtypes == 'object'].index)


# for col in string_columns:
#     df[col] = df[col].str.lower().str.replace(' ', '_')
    
# df

laptop       status   brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           model                cpu  ram  storage storage_type       gpu  \
0     ExpertBook      Intel Core i5    8      512          SSD       NaN   
1             Go      Intel Celeron    8      256          SSD       NaN   
2     ExpertBook      Intel Core i3    8      256          SSD       NaN   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2159        Book  Intel Evo Core i7   16      256          SSD       NaN   

      screen touch  final_price  
0       15.6    No      1009.00  
1       15.6    No       299.00  
2       15.6    No       789.00  
3       15.6    No      1199.00  
4       15.6    No       669.01  
...      ...   ...          ...  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  
2159    13.4   Yes      1699.99  

[2160 rows x 12 columns]

In [7]:
df.isnull().sum()

laptop             0
status             0
brand              0
model              0
cpu                0
ram                0
storage            0
storage_type      42
gpu             1371
screen             4
touch              0
final_price        0
dtype: int64

In [6]:
df['brand'].value_counts().head(27)

brand
Asus                415
HP                  368
Lenovo              366
MSI                 308
Acer                137
Apple               116
Dell                 84
Microsoft            77
Gigabyte             48
Razer                37
Medion               32
LG                   32
Alurin               29
PcCom                24
Samsung              22
Dynabook Toshiba     19
Vant                 11
Deep Gaming           8
Primux                8
Innjoo                6
Thomson               4
Prixton               3
Millenium             2
Denver                1
Jetwing               1
Realme                1
Toshiba               1
Name: count, dtype: int64

In [10]:
df_dell = df[df['brand']== 'Dell']
df_dell.sort_values('final_price')

laptop       status brand  \
633   Dell Latitude E5440 Intel Core i5-4310U/8GB/12...  Refurbished  Dell   
1843  Dell Vostro 5301 Intel Core i5-1135G7/8GB/256G...  Refurbished  Dell   
809   Dell Latitude E7450 Intel Core i5-5300U/8GB/25...  Refurbished  Dell   
1836  Dell Latitude 5480 Intel Core i5-7300U/8GB/256...  Refurbished  Dell   
1839  Dell Latitude E5550 Intel Core i5-5300U/8GB/12...  Refurbished  Dell   
...                                                 ...          ...   ...   
1323  Dell Latitude 5520 Intel Core i5-1135G7/8GB/25...          New  Dell   
1347  Dell XPS 15 9520 Intel Core i7-12700H/32GB/1TB...  Refurbished  Dell   
1346  Dell XPS 15 9520 Intel Core i7-12700H/16GB RAM...          New  Dell   
1334  Dell Precision 5470 Intel Core i7-12800H/16GB/...          New  Dell   
1335  Dell Precision 5770 Intel Core i7-12700H/16GB/...          New  Dell   

          model            cpu  ram  storage storage_type        gpu  screen  \
633    Latitude  Intel Core i5    8      128          SSD        NaN    14.0   
1843     Vostro  Intel Core i5    8      256          SSD        NaN    13.3   
809    Latitude  Intel Core i5    8      256          SSD        NaN    14.0   
1836   Latitude  Intel Core i5    8      256          SSD        NaN    14.0   
1839   Latitude  Intel Core i5    8      128          SSD        NaN    15.6   
...         ...            ...  ...      ...          ...        ...     ...   
1323   Latitude  Intel Core i5    8      256          SSD        NaN    15.6   
1347        XPS  Intel Core i7   32     1000          SSD   RTX 3050    15.6   
1346        XPS  Intel Core i7   16     1000          SSD   RTX 3050    15.6   
1334  Precision  Intel Core i7   16      512          SSD  RTX A1000    14.0   
1335  Precision  Intel Core i7   16      512          SSD  RTX A2000    17.0   

     touch  final_price  
633     No       379.00  
1843    No       420.74  
809     No       448.99  
1836    No       489.00  
1839    No       489.00  
...    ...          ...  
1323    No      2450.71  
1347   Yes      2818.09  
1346    No      3012.09  
1334    No      3469.00  
1335   Yes      3936.00  

[84 rows x 12 columns]

In [11]:
median_screen = df['screen'].median()
print('median screen :', median_screen)

median screen : 15.6


In [14]:
most_frequent_screen = df['screen'].mode()[0]
print('most frequent screen :', most_frequent_screen)

most frequent screen : 15.6


In [15]:
df['screen'].fillna(df['screen'].mode()[0], inplace=True)

/tmp/ipykernel_383902/2225398897.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['screen'].fillna(df['screen'].mode()[0], inplace=True)


In [16]:
df.isnull().sum()

laptop             0
status             0
brand              0
model              0
cpu                0
ram                0
storage            0
storage_type      42
gpu             1371
screen             0
touch              0
final_price        0
dtype: int64

In [17]:
median_screen = df['screen'].median()
print('median screen :', median_screen)

median screen : 15.6


Q7=  Sum of weights

In [24]:
df_injoo = df[df['brand']== 'Innjoo']
df_injoo = df_injoo[['ram', 'storage', 'screen']]
df_injoo

ram  storage  screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [40]:
X = df_injoo.to_numpy()

X_T = X. T
XTX = np.dot(X_T, X)  
print(XTX)




[[2.52000e+02 8.32000e+03 5.59800e+02]
 [8.32000e+03 3.68640e+05 1.73952e+04]
 [5.59800e+02 1.73952e+04 1.28196e+03]]


In [45]:
# y = np.array([1100, 1300, 800, 900, 1000, 1100])
y = [1100, 1300, 800, 900, 1000, 1100]
y

[1100, 1300, 800, 900, 1000, 1100]

In [48]:
XTX_inv = np.linalg.inv(XTX)
result = np.dot(XTX_inv, X_T)
result

array([[ 0.26298349, -0.12560233, -0.40646389,  0.14958687,  0.05244042,
         0.05244042],
       [-0.00110155,  0.00295059,  0.00125892, -0.00177691, -0.00076387,
        -0.00076387],
       [-0.08772226,  0.0269791 ,  0.17140891, -0.0302108 , -0.00153546,
        -0.00153546]])

In [49]:
w = np.dot(result, y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [50]:
sum_w = np.sum(w)
sum_w

np.float64(91.2998806299555)

In [51]:
pd.__version__

'2.2.2'